// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Model.Models;
using System;
using System.Collections.Generic;

namespace Model.Models.Configurations
{
    public partial class EmpleadoConfiguration : IEntityTypeConfiguration<Empleado>
    {
        public void Configure(EntityTypeBuilder<Empleado> entity)
        {
            entity.Property(e => e.Id).HasColumnName("id");

            entity.Property(e => e.IdCargo).HasColumnName("id_cargo");

            entity.Property(e => e.IdEmpresa).HasColumnName("id_empresa");

            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("nombre");

            entity.HasOne(d => d.IdCargoNavigation)
                .WithMany(p => p.Empleado)
                .HasForeignKey(d => d.IdCargo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Empleado__id_car__3C69FB99");

            entity.HasOne(d => d.IdEmpresaNavigation)
                .WithMany(p => p.Empleado)
                .HasForeignKey(d => d.IdEmpresa)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Empleado__id_emp__3B75D760");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Empleado> entity);
    }
}
