// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models
{
    public partial class Cargo
    {
        public Cargo()
        {
            Empleado = new HashSet<Empleado>();
        }

        public int Id { get; set; }
        public string Descripcion { get; set; }
        public decimal? Salario { get; set; }

        public virtual ICollection<Empleado> Empleado { get; set; }
    }
}