// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Model.Models.Configurations;
using System;
using System.Collections.Generic;
#nullable disable

namespace Model.Models
{
    // Clase generada al utilizar "reverse engineer" del EF Core Power Tools
    public partial class OrganizacionContext : DbContext
    {
        public OrganizacionContext()
        {
        }

        public OrganizacionContext(DbContextOptions<OrganizacionContext> options)
            : base(options)
        {
        }

        // Estan definidas las tablas con el objeto DbSet<T>
        public virtual DbSet<Cargo> Cargo { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }

        //Dentro de cada configuration esta la representacion en C# de la estructura de las tablas que tenemos en nuestra BDD
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new Configurations.CargoConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.EmpleadoConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.EmpresaConfiguration());

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
